[repository]
name = "hyprshortcuts"
authors = ["0x42697262"]

[hyprshortcuts]
description = "Keybind cheatsheet overlay for Hyprland (like AwesomeWM's helper)"
authors = ["0x42697262"]
output = "hyprshortcuts.so"
build = ["make all"]
